import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArticleToc, DocsSidebar, DocumentPager, MarkdownArticle } from "../../../components/docs/docs-components";
import { publicDocuments } from "../../../lib/docs/manifest";
import { getAllDocuments, getDocument } from "../../../lib/docs/repository";
const canonicalBase = "https://typechain.theorvane.tech";
export function generateStaticParams() { return publicDocuments.map((d)=>({ slug:d.route.replace("/docs/","").split("/") })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string[] }> }): Promise<Metadata> { const route=`/docs/${(await params).slug.join("/")}`; const document=await getDocument(route); if (!document) return {}; return { title:`${document.title} | TypeChain`, description:document.document.summary, alternates:{canonical:route}, openGraph:{title:`${document.title} | TypeChain`,description:document.document.summary,url:`${canonicalBase}${route}`}}; }
export default async function DocumentPage({ params }: { params: Promise<{ slug: string[] }> }) { const route=`/docs/${(await params).slug.join("/")}`; const [documents,document]=await Promise.all([getAllDocuments(),getDocument(route)]); if(!document) notFound(); return <><a className="skip-link" href="#docs-content">Skip to documentation</a><header className="docs-header"><a className="logo" href="/">TYPE<span>CHAIN</span></a><nav aria-label="Primary"><a href="/">Product</a><a href="/docs">Documentation</a><a href="https://github.com/Theorvane/type-chain" target="_blank" rel="noopener noreferrer">GitHub</a></nav></header><main className="docs-layout"><DocsSidebar documents={documents} activeRoute={route}/><MarkdownArticle document={document}/><DocumentPager documents={documents} route={route}/><ArticleToc document={document}/></main></>; }
