import { DocsSidebar } from "../../components/docs/docs-components";
import { getAllDocuments } from "../../lib/docs/repository";
import { sourceCommit } from "../../lib/docs/manifest";

export default async function DocsIndex() {
  const documents = await getAllDocuments();
  const groups = ["Start", "Guides", "API", "Architecture", "Product"] as const;
  return <><a className="skip-link" href="#docs-content">Skip to documentation</a><header className="docs-header"><a className="logo" href="/">TYPE<span>MCP</span></a><nav aria-label="Primary"><a href="/">Product</a><a href="/docs" aria-current="page">Documentation</a><a href="https://github.com/Theorvane/type-mcp" target="_blank" rel="noopener noreferrer">GitHub <span className="sr-only">(opens in a new tab)</span></a><a href="https://www.npmjs.com/package/type-mcp" target="_blank" rel="noopener noreferrer">npm <span className="sr-only">(opens in a new tab)</span></a></nav></header><main className="docs-layout"><DocsSidebar documents={documents} /><article id="docs-content" className="docs-index"><p className="eyebrow">TypeMCP technical documentation</p><h1>TypeMCP documentation</h1><p>The published npm package provides decorator declarations and immutable metadata reads. Repository-development documents describe work that is not installed API until it appears in a released package.</p><aside className="release-callout"><strong>Read the release boundary first</strong><p><code>type-mcp@0.1.0</code> does not validate, compile, invoke, or transport MCP operations.</p></aside>{groups.map((group) => <section key={group}><h2>{group}</h2><div className="docs-card-grid">{documents.filter((document) => document.document.group === group).map((document) => <a className="docs-card" href={document.document.route} key={document.document.route}><strong>{document.document.title}</strong><span>{document.document.summary}</span></a>)}</div></section>)}<p className="source-link"><a href={`https://github.com/Theorvane/type-mcp/tree/${sourceCommit}/docs`} target="_blank" rel="noopener noreferrer">Documentation source pinned to {sourceCommit.slice(0, 12)} <span className="sr-only">(opens in a new tab)</span></a></p></article></main></>;
}
