import { documentGroups, type PublicDocument } from "./types";

// Pin only after the canonical TypeChain documentation source is promoted to main.
export const sourceCommit = "edb33a1a074b2a92c8a294313d046ac8ebbd930b";

const documents: readonly PublicDocument[] = [
  { sourcePath: "docs/guides/getting-started.md", route: "/docs/getting-started", title: "Getting started", summary: "Install TypeChain, configure Stage 3 decorators, and declare a first tool.", group: "Start", order: 1, classification: "published", sourceStatus: "@theorvane/type-chain@0.1.1" },
  { sourcePath: "docs/guides/core-concepts.md", route: "/docs/core-concepts", title: "Core concepts", summary: "Understand tool metadata, immutable definitions, policy intent, and explicit integration boundaries.", group: "Start", order: 2, classification: "published", sourceStatus: "@theorvane/type-chain@0.1.1" },
  { sourcePath: "docs/guides/petstore-walkthrough.md", route: "/docs/petstore-walkthrough", title: "Petstore walkthrough", summary: "Build one typed catalog tool, then choose a LangChain, agent, or in-process TypeMCP boundary.", group: "Start", order: 3, classification: "published", sourceStatus: "@theorvane/type-chain@0.1.1" },
  { sourcePath: "docs/guides/tools-and-definitions.md", route: "/docs/guides/tools-and-definitions", title: "Tools and definitions", summary: "The @Tool() contract, immutable definitions, and inheritance.", group: "Guides", order: 1, classification: "published", sourceStatus: "@theorvane/type-chain@0.1.1" },
  { sourcePath: "docs/guides/policy.md", route: "/docs/guides/policy", title: "Policy and guards", summary: "Declarative policy intent with application-owned enforcement.", group: "Guides", order: 2, classification: "published", sourceStatus: "@theorvane/type-chain@0.1.1" },
  { sourcePath: "docs/guides/langchain-integration.md", route: "/docs/guides/langchain-integration", title: "LangChain integration", summary: "Adapt decorated methods into standard LangChain tools.", group: "Guides", order: 3, classification: "published", sourceStatus: "@theorvane/type-chain@0.1.1" },
  { sourcePath: "docs/guides/agent-builder.md", route: "/docs/guides/agent-builder", title: "Agent builder", summary: "Build LangChain agents while retaining application control.", group: "Guides", order: 4, classification: "published", sourceStatus: "@theorvane/type-chain@0.1.1" },
  { sourcePath: "docs/guides/typemcp-bridge.md", route: "/docs/guides/typemcp-bridge", title: "TypeMCP bridge", summary: "Compose a TypeMCP server into LangChain tools in process.", group: "Guides", order: 5, classification: "published", sourceStatus: "@theorvane/type-chain@0.1.1" },
  { sourcePath: "docs/guides/composition-selection.md", route: "/docs/guides/composition-selection", title: "Choose a composition boundary", summary: "Choose metadata, LangChain, agent, or in-process TypeMCP composition.", group: "Guides", order: 6, classification: "published", sourceStatus: "@theorvane/type-chain@0.1.1" },
  { sourcePath: "docs/api/decorator-api.md", route: "/docs/api/decorator-api", title: "Decorator API contract", summary: "Published exports and integration boundaries.", group: "API", order: 1, classification: "published", sourceStatus: "@theorvane/type-chain@0.1.1" },
  { sourcePath: "docs/architecture.md", route: "/docs/architecture", title: "Architecture", summary: "Decorator-first LangChain authoring architecture.", group: "Architecture", order: 1, classification: "published-with-boundary", sourceStatus: "TypeChain does not enforce runtime policy." },
];
export const publicDocuments = Object.freeze(documents.map((document) => Object.freeze({ ...document })));
export function isSafeSourcePath(sourcePath: string): boolean { return /^docs\/(?:[A-Za-z0-9][A-Za-z0-9._-]*\/)*[A-Za-z0-9][A-Za-z0-9._-]*\.md$/.test(sourcePath) && !sourcePath.includes("..") && !sourcePath.includes("\\"); }
export function validateManifest(manifest: readonly PublicDocument[]): void { if (!/^[0-9a-f]{40}$/.test(sourceCommit)) throw new Error("source commit must be a full SHA"); const routes = new Set<string>(); const paths = new Set<string>(); const orders = new Set<string>(); for (const document of manifest) { if (!isSafeSourcePath(document.sourcePath) || /(?:^|\/)(?:planning|superpowers)(?:\/|$)/.test(document.sourcePath)) throw new Error(`approved docs source path required: ${document.sourcePath}`); if (!document.route.startsWith("/docs/") || document.route.includes("..")) throw new Error(`approved docs route required: ${document.route}`); if (!document.sourceStatus.trim()) throw new Error(`source status evidence required: ${document.sourcePath}`); if (routes.has(document.route) || paths.has(document.sourcePath) || orders.has(`${document.group}:${document.order}`)) throw new Error(`duplicate manifest entry: ${document.route}`); if (!documentGroups.includes(document.group)) throw new Error(`unknown document group: ${document.group}`); routes.add(document.route); paths.add(document.sourcePath); orders.add(`${document.group}:${document.order}`); } }
validateManifest(publicDocuments);
