import { ExternalLink, SkipLink } from "@theorvane/ui";

const github = "https://github.com/Theorvane/type-mcp";
const npm = "https://www.npmjs.com/package/type-mcp";

export default function HomePage() { return <><SkipLink /><header className="shell"><a className="logo" href="#top">type<span>mcp</span></a><nav aria-label="Primary"><a href="#overview">Overview</a><a href="#architecture">Architecture</a><a href="#integrations">Integrations</a><ExternalLink className="nav-cta" href={github}>View on GitHub ↗</ExternalLink></nav></header><main id="main-content"><section className="hero shell" id="top"><div><p className="eyebrow">TypeScript · MCP · Explicit contracts</p><h1>Decorator-first MCP.<br/><em>Built for boundaries.</em></h1><p>Define tools with familiar TypeScript decorators, compile them into safe MCP definitions, and keep application framework choices at the edge.</p><div className="actions"><ExternalLink className="button primary" href={github}>View on GitHub ↗</ExternalLink><ExternalLink className="button" href={npm}>npm package ↗</ExternalLink></div></div><pre><code>{`@McpServer({ name: "catalog" })
class CatalogTools {
  @McpTool({
    name: "find_product",
    description: "Find a product by id",
  })
  findProduct(input: { id: string }) {
    return this.catalog.get(input.id);
  }
}`}</code></pre></section><section className="capabilities shell" id="overview"><article><b>01</b><h2>Decorators → metadata</h2><p>Declare intent close to your code without losing explicit definitions.</p></article><article><b>02</b><h2>Validated runtime core</h2><p>Compile schemas and handlers into predictable MCP contracts.</p></article><article><b>03</b><h2>Resolver boundary</h2><p>Bring your own instances, lifecycle, and application framework.</p></article></section><section className="architecture shell" id="architecture"><p className="eyebrow">Architecture</p><h2>Declarations in.<br/>Portable runtime out.</h2><ol><li><span>01</span> Decorated TypeScript class</li><li><span>02</span> Metadata and schema validation</li><li><span>03</span> Resolver-backed execution</li><li><span>04</span> MCP transport at the edge</li></ol></section><section className="integration shell" id="integrations"><p className="eyebrow">LangChain + LangGraph</p><div className="integration-grid"><div><h2>Metadata first. Runtime later.</h2><p><code>type-mcp@0.1.0</code> records standard decorator metadata. It does not compile, invoke, or transport decorated tools as MCP operations.</p><p><code>createMcpServer()</code> and <code>type-mcp/http</code> / <code>createMcpHandler()</code> are reserved and throw in the published release. Applications need their own runnable MCP integration until a later TypeMCP release.</p></div><aside><strong>Release boundary</strong><p>Published <code>type-mcp@0.1.0</code> is the current npm release. The repository currently exports its framework-neutral runtime and <code>./http</code> subpath; future adapter work must not be treated as released API.</p></aside></div></section><section className="start shell"><p className="eyebrow">Get started</p><h2>Inspect the source.<br/>Start with a tool.</h2><div className="actions"><ExternalLink className="button primary" href={github}>View on GitHub ↗</ExternalLink><ExternalLink className="button" href={npm}>npm package ↗</ExternalLink></div></section></main><footer className="shell"><span>TypeMCP is open source by <ExternalLink href="https://github.com/Theorvane">Theorvane ↗</ExternalLink></span><ExternalLink href={github}>GitHub ↗</ExternalLink></footer></>; }
