import { ExternalLink, SkipLink } from "@theorvane/ui";

const github = "https://github.com/Theorvane/type-mcp";
const npm = "https://www.npmjs.com/package/type-mcp";

export default function HomePage() { return <><SkipLink /><header className="shell"><a className="logo" href="#top">type<span>mcp</span></a><nav aria-label="Primary"><a href="#overview">Overview</a><a href="#architecture">Architecture</a><a href="#integrations">Integrations</a><ExternalLink className="nav-cta" href={github}>View on GitHub ↗</ExternalLink></nav></header><main id="main-content"><section className="hero shell" id="top"><div><p className="eyebrow">TypeScript · MCP · Explicit contracts</p><h1>Decorator-first MCP.<br/><em>Built for boundaries.</em></h1><p>Record MCP declarations with familiar TypeScript decorators. In the published 0.1.0 release, those declarations remain inspectable metadata only.</p><div className="actions"><ExternalLink className="button primary" href={github}>View on GitHub ↗</ExternalLink><ExternalLink className="button" href={npm}>npm package ↗</ExternalLink></div></div><pre><code>{`@McpServer({ name: "catalog" })
class CatalogTools {
  @McpTool({
    name: "find_product",
    description: "Find a product by id",
  })
  findProduct(input: { id: string }) {
    return this.catalog.get(input.id);
  }
}`}</code></pre></section><section className="capabilities shell" id="overview"><article><b>01</b><h2>Decorators → metadata</h2><p>Declare intent close to your code without losing explicit definitions.</p></article><article><b>02</b><h2>Immutable metadata reads</h2><p>Inspect declared server and tool options without starting an MCP runtime.</p></article><article><b>03</b><h2>Explicit release boundary</h2><p>Keep 0.1.0 declaration-only while future runtime work remains unreleased.</p></article></section><section className="architecture shell" id="architecture"><p className="eyebrow">Architecture</p><h2>Declarations in.<br/>Metadata out.</h2><ol><li><span>01</span> Decorated TypeScript class</li><li><span>02</span> Immutable metadata inspection</li><li><span>03</span> Application-owned runtime choice</li><li><span>04</span> No published MCP transport in 0.1.0</li></ol></section><section className="integration" id="integrations"><div className="shell integration-content"><p className="eyebrow">Published release boundary</p><div className="integration-grid"><div><h2>Metadata first. Runtime later.</h2><p><code>type-mcp@0.1.0</code> records standard decorator metadata. It does not validate, compile, invoke, or transport decorated tools as MCP operations.</p><p><code>createMcpServer()</code> and <code>type-mcp/http</code> / <code>createMcpHandler()</code> are reserved and throw in the published release. Applications need their own runnable MCP integration until a later TypeMCP release.</p></div><aside><strong>Release boundary</strong><p>Published <code>type-mcp@0.1.0</code> is declaration-only. Repository-source work may evolve separately, but it must not be treated as released npm API until published.</p></aside></div></div></section><section className="start shell"><p className="eyebrow">Get started</p><h2>Inspect the source.<br/>Start with a tool.</h2><div className="actions"><ExternalLink className="button primary" href={github}>View on GitHub ↗</ExternalLink><ExternalLink className="button" href={npm}>npm package ↗</ExternalLink></div></section></main><footer className="shell"><span>TypeMCP is open source by <ExternalLink href="https://github.com/Theorvane">Theorvane ↗</ExternalLink></span><ExternalLink href={github}>GitHub ↗</ExternalLink></footer></>; }
